Cloud bastion
Otus-DevOps-2021-02/vladlind_infra pull request #1
Opened 2021-03-19 06:27 UTC by vladlind

2021-03-20 13:46 UTC, mrgreyves requested changes
Здравствуйте!) Нужно добавить описание к вашему пр, дз возвращаю на доработку.
![image](https://user-images.githubusercontent.com/34331259/111871546-cd2ac300-899b-11eb-96ea-501d58710ed0.png)

2021-03-20 18:01 UTC, vladlind commented
Здравствуйте, описание ПР добавил

2021-03-21 18:40 UTC, mrgreyves requested changes
Здравствуйте!) Вам стоит обратить внимание на тесты, к сожалению много ошибок, дз возвращаю в доработку =(

2021-03-22 04:54 UTC, vladlind commented
Здравствуйте, вообще-то тесты ко второй и третьей ДЗ проходят без ошибок - https://github.com/Otus-DevOps-2021-02/vladlind_infra/pull/1/commits/93508e5cedb2804422e80feb9a665b3565e579a5
Вот с 4-ой ДЗ возникли проблемы - о них я задал вопрос в чате с рабочем кабинета отуса.

2021-03-22 05:45 UTC, mrgreyves approved these changes
Здравствуйте!) Мы с вами как раз говорим про конкретную дз, так же если у вас есть вопросы, с ними стоит обращаться в слак. Теперь с дз все хорошо, принимаю!=)

2021-03-22 06:38 UTC, merged